name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.3.3
    - name: Start CI Tests
      run: echo Tests started for Kunena Forum
    - name: Composer & Npm Install
      run: |
       composer validate --no-check-all --strict
       composer install --no-progress --no-suggest
       npm install selenium-standalone
